### ISSUE TITLE
Cannot run or import your project.

### ISSUE THREAD

**Issue by Sosko** [vikramarsid/msg_parser#19]
Cannot run or import your project.
After run it from shell this error appear:

```
Traceback (most recent call last):
  File "/usr/local/bin/msg_parser", line 11, in <module>
    load_entry_point('msg-parser==1.0.0', 'console_scripts', 'msg_parser')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/msg_parser-1.0.0-py3.6.egg/msg_parser/__init__.py", line 5, in <module>
    from msg_parser import MsOxMessage
ImportError: cannot import name 'MsOxMessage'
```

When I try to import this happens:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msg_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/msg_parser-1.0.0-py3.6.egg/msg_parser/__init__.py", line 5, in <module>
    from msg_parser import MsOxMessage
ImportError: cannot import name 'MsOxMessage'
```

Run on:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by crameth** [comment]
also having the same problem

**Comment by bernhardreiter** [comment]
Also here.
Additionally when entering the directory manually, there is a different problem:

```sh
cd ~/.local/lib/python3.5/site-packages/msg_parser
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msg_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bern/.local/lib/python3.5/site-packages/msg_parser/msg_parser.py", line 14, in <module>
    from data_models import DataModel
  File "/home/bern/.local/lib/python3.5/site-packages/msg_parser/data_models.py", line 5, in <module>
    from properties import DATA_TYPE_MAP
  File "/home/bern/.local/lib/python3.5/site-packages/msg_parser/properties/__init__.py", line 3, in <module>
    from ms_props_date_type_map import DATA_TYPE_MAP
ImportError: No module named 'ms_props_date_type_map'
>>> 
```

**Comment by bernhardreiter** [comment]
This seems to be an issue with Python3 compatibility.
Adding a few "." to the imports at least got it imported for me.

Like changing a number of import lines to relative imports like for example
```python
from .msg_parser import MsOxMessage
```
(note the leading `.`).

But then I run into
```sh
.local/lib/python3.5/site-packages/msg_parser/msg_parser.py", line 447, in is_valid_msg_file
    if not os.path.exists(self.msg_file_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not _io.TextIOWrapper
```

**Comment by bernhardreiter** [comment]
The problem with is_valid_msg_file from the argument parser that does not parse a file_path, but an open file object. When changing this, there are still problems in python2 and python3. So giving up for now.

**Comment by crameth** [comment]
i resorted to using http://timgolden.me.uk/pywin32-docs/html/com/win32com/HTML/QuickStartClientCom.html to parse my .msg files in the end. skip this repo, it's useless in its current state.

if win32com.client is insufficient, you can always convert the .msg files to a more widely supported format to parse through python libraries (e.g. .eml format, i heard that's quite well supported on python).

**Comment by joelgenter** [comment]
This is an issue for me as well. Running
```python
from msg_parser import MsOxMessage
```
yields
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/wlanalyzer/lib/python3.7/site-packages/msg_parser/__init__.py", line 5, in <module>
    from msg_parser import MsOxMessage
ImportError: cannot import name 'MsOxMessage' from 'msg_parser' (/anaconda3/envs/wlanalyzer/lib/python3.7/site-packages/msg_parser/__init__.py)
```

**Comment by chervaliery** [comment]
I'm also interested in python3 compatibility.

**Comment by archellepagapulan** [comment]
any resolution on this?

**Comment by vikramarsid** [comment]
Add python3 support this week.

**Comment by Ousret** [comment]
PR proposed 🎉
